#!/usr/bin/env bash
# Copyright 2020 Gentoo Authors
# Distributed under the terms of the GNU General Public License v3 (or any later version)
set -euo pipefail

while getopts :d OPT; do
	case $OPT in
		d)
			set -x
			;;
		*)
			echo "usage: ${0##*/} [-d]"
			exit 2
	esac
done

readonly GENTOO_PROFILE_ENV_PATH="/etc/profile.env"
readonly GENTOO_SYSTEMD_ENV_CONF="/usr/lib/environment.d/gentoo-env.conf"

# Strip "export " to transform gentoo's profile.env syntax, which is
# shell, to systemd's environment.d syntax (which is shell-like
# without explicit "export" keyword).
readonly STRIP_EXPORT_REGEX="s;^export ;;"
# Strip comments.
readonly STRIP_COMMENTS_REGEX="/^[ \t]*#/d"
readonly STRIP_EMPTY_LINES_REGEX="/^[ \t]*$/d"

sed -e "${STRIP_EXPORT_REGEX}" \
	-e "${STRIP_COMMENTS_REGEX}" \
	-e "${STRIP_EMPTY_LINES_REGEX}" \
	"${GENTOO_PROFILE_ENV_PATH}" \
	> "${GENTOO_SYSTEMD_ENV_CONF}"
