#!/usr/bin/env bash
set -euo pipefail

EMERGE_OPTS=(
	--complete-graph
	--keep-going
	--oneshot
	--tree
	--verbose
	--backtrack 100
)

EMERGE_UPDATE_OPTS=(
	--update
	--changed-use
)

ONLY_WORLD=false
DEBUG=false
PRETEND=false
SYNC=false
BE_ULTRA_NICE=false
JOBS=""
LOAD_PERCENTAGE=""
DEPCLEAN=true
EMERGE_ONCE=true
USEPKG=true
RESTART_SERVICES=true
MAYBE_PRETEND=""
UNATTENDED_REBOOT=false
UNATTENDED_REBOOT_AFTER_DAYS=19
ECLEAN_KERNEL=true

command-exists() {
	if command -v $@ &> /dev/null; then
		return 0
	fi
	return 1
}

declare -i EXIT_INVALID_OPT=1
declare -i EXIT_NO_NETWORK=2
declare -i EXIT_EMERGE_FAILED=3
declare -i EXIT_GLSA_FIX_FAILED=4
declare -i EXIT_FAILED_COMMANDS=5

while getopts "cdj:l:no:pr:sw" OPTION; do
    case $OPTION in
	c)
		DEPCLEAN=false
		;;
	d)
	    DEBUG=true
	    ;;
	j)
		JOBS=${OPTARG}
		;;
	l)
		LOAD_PERCENTAGE="${OPTARG}"
		# TODO: Ensure that LOAD_PERCENTAGE is a non-negative float.
		;;
	n)
		BE_ULTRA_NICE=true
		;;
	o)
		EMERGE_ONCE=${OPTARG}
		# TODO: Check if OPTARG is true/false.
		;;
	p)
	    PRETEND=true
		MAYBE_PRETEND="--pretend"
	    ;;
	s)
		SYNC=true
		;;
	r)
		case "${OPTARG}" in
			true|false)
				RESTART_SERVICES="${OPTARG}"
				;;
		esac
		;;
	w)
	    ONLY_WORLD=true
	    ;;
	*)
		echo "Invalid option: ${OPTION}"
		exit "${EXIT_INVALID_OPT}"
    esac
done

if $DEBUG; then
	set -x
fi

declare -i WORLD_UPDATE_EVERY_DAYS=51
declare -i SMART_LIVE_REBUILD_EVERY_DAYS=14
ECLEAN_DISTFILES_ARGS=

GENTOOLS_CONFIG_FILE="/etc/gentools/update-system.config"
if [[ -f "${GENTOOLS_CONFIG_FILE}" ]]; then
	source "${GENTOOLS_CONFIG_FILE}"
fi

REBOOT=false

MAYBE_EMERGE_USEPKG_OPT=""
if $USEPKG; then
	MAYBE_EMERGE_USEPKG_OPT="--usepkg y"
fi

if [[ -f /usr/bin/systemd-inhibit && ! -v UPDATE_SYSTEMD_INHIBITED ]]; then
	export UPDATE_SYSTEMD_INHIBITED=true

	# After the system woke up, it may be still in 'sleep' state for a
	# brief period. This causes sytemd-inhitit to fail with "Failed to
	# inhibit: The operation inhibition has been requested for is
	# already running". Therefore, we have to potentially try multiple
	# times until we can take the sleep inhibit lock. See
	# https://github.com/systemd/systemd/issues/14045
	declare -ir WAIT_INHIBITED_SECS=180
	for I in $(seq 0 ${WAIT_INHIBITED_SECS}); do
		if [[ ${I} -eq ${WAIT_INHIBITED_SECS} ]]; then
			>&2 echo "Failed to take inhibit lock after ${I} seconds"
			exit ${SYSTEMD_INHIBIT_RET}
		fi
		# Check if we would be able to take the inhibit lock.
		if /usr/bin/systemd-inhibit true; then
			if [[ ${I} -ne 0 ]]; then
				echo "Inhibit lock free after ${I} seconds"
			fi
			break
		fi
		SYSTEMD_INHIBIT_RET=$?
		sleep 1
	done
	exec /usr/bin/systemd-inhibit \
		 --what="shutdown:sleep" \
		 --who="update-system" \
		 --why="Prevent system sleep and shutdown during system update" \
		 "${0}" "${@}"
fi


WAIT_NETWORK_SECS=180
PING_HOST=gentoo.org
for I in $(seq 1 ${WAIT_NETWORK_SECS}); do
	if [[ ${I} -eq ${WAIT_NETWORK_SECS} ]]; then
		# Last ping without stderr redirection.
		if ping -c 1 ${PING_HOST} > /dev/null; then
			break
		else
			>&2 echo "Network not online after ${WAIT_NETWORK_SECS} seconds"
			exit "${EXIT_NO_NETWORK}"
		fi
	fi
	if ping -c 1 ${PING_HOST} &> /dev/null; then
		# Network is available and online.
		break
	fi
	echo "Waiting for network [ping ${PING_HOST}]… (${I})"
	sleep 1
done

# Disable iwdevtools, if installed, for update-system runs.
export IWDT_ALL=n

CORES=$(nproc)

if $BE_ULTRA_NICE || [[ -n "${LOAD_PERCENTAGE}" ]]; then
	if [[ -z "${LOAD_PERCENTAGE}" ]]; then
		LOAD_PERCENTAGE="0.85"
	fi

	MAKE_LOAD=$(echo "${CORES} * ${LOAD_PERCENTAGE}" | bc)

	if [[ "${MAKE_LOAD%.*}" -lt 1 ]]; then
		MAKE_LOAD="2"
		MAKE_JOBS="1"
	else
		MAKE_JOBS="${MAKE_LOAD%.*}"
	fi

	# Limit the number of jobs also based on the available
	# memory. Assumes one job per GiB memory available, scaled via
	# LOAD_PERCENTAGE.
	MEM_GIB=$(LANG=C free -g|awk '/^Mem:/{print $2}')
	MEM_GIB_PERCENTAGE=$(echo "${MEM_GIB} * ${LOAD_PERCENTAGE}" | bc)
	MEM_GIB_PERCENTAGE_INTEGER="${MEM_GIB_PERCENTAGE%.*}"
	if [[ "${MEM_GIB_PERCENTAGE_INTEGER}" -lt 1 ]]; then
		MAKE_JOBS="1"
	elif [[  "${MEM_GIB_PERCENTAGE_INTEGER}" -lt "${MAKE_JOBS}" ]]; then
		MAKE_JOBS="${MEM_GIB_PERCENTAGE_INTEGER}"
	fi

	export MAKEOPTS="--jobs=${MAKE_JOBS} --load-average=${MAKE_LOAD}"
fi

if [[ -z ${JOBS} ]]; then
	JOBS=$((CORES / 4))
	if [[ ${JOBS} -gt 1 ]]; then
		EMERGE_OPTS+=("--jobs=${JOBS}")
	else
		JOBS=1
	fi
fi


printUpgradeablePackages() {
		cat <<EOF
The following ${#UPGRADEABLE_PACKAGES[@]} outdated packages (${1}) where found:
--------------------------------------------
$(printf '%s\n' "${UPGRADEABLE_PACKAGES[@]}")
--------------------------------------------
Attempting to update those packages
EOF
}

FAILED_COMMANDS=()

run() {
	runCommand=()
	if $BE_ULTRA_NICE; then
		runCommand+=("chrt --idle 0 ionice -c idle")
	fi

	# shellcheck disable=SC2068
	runCommand+=(${@})

	RUN_FAILED=false

	echo ${*}

	set +e
	# shellcheck disable=SC2068
	${runCommand[@]}
	local exit_status=$?
	set -e

	if [[ ${exit_status} -gt 0 ]]; then
		RUN_FAILED=true
		local failure_level
		if [[ -v DO_NOT_RECORD_FAILURE ]]; then
			failure_level=INFO
		else
			FAILED_COMMANDS+=( "${*}" )
			failure_level=ERROR
		fi

		>&2 echo "${failure_level}: ${*} return failure status ${exit_status}"
	fi

	# Do not return $exit_status here, as we want commands invoked
	# with 'run' to be non-fatal.
}

if $SYNC; then
	run emerge --sync --verbose

	# Only invoke update is /var/cache/eix/remote.eix is not from today.
	EIX_REMOTE_UPDATE=true
	EIX_REMOTE_FILE="/var/cache/eix/remote.eix"
	if [[ -f ${EIX_REMOTE_FILE} ]]; then
		EIX_REMOTE_FILE_DATE=$(stat --format=%y "${EIX_REMOTE_FILE}" |cut -d ' ' -f 1)
		CURRENT_DATE=$(date -I)

		if [[ "${EIX_REMOTE_FILE_DATE}" == "${CURRENT_DATE}" ]]; then
			echo "${EIX_REMOTE_FILE} is from today, skipping \"eix-remote update\""
			EIX_REMOTE_UPDATE=false
		fi
	fi

	if $EIX_REMOTE_UPDATE; then
		run eix-remote update
	fi
fi

determineObsoletePackages() {
	local obsolete_packages
	obsolete_packages=$(TEST_FOR_REDUNDANCY=false \
						TEST_FOR_NONEXISTENT=true \
										   eix \
										   --test-obsolete \
										   --only-names \
										   || true)

	for obsolete_package in ${obsolete_packages}; do
		# shellcheck disable=SC2091
		if $(FORMAT='{upgrade}true{else}false{}' eix --exact --pure-packages "${obsolete_package}"); then
			# TODO: Take slots into account. If the currently
			# installed slot is upgradeable, then use this
			# slot. Otherwhise use the newest stable stlot.
			UPGRADEABLE_PACKAGES+=("${obsolete_package}")
		else
			NON_UPGRADEABLE_PACKAGES+=("${obsolete_package}")
		fi
	done
}

initPackagesArrays() {
	UPGRADEABLE_PACKAGES=()
	NON_UPGRADEABLE_PACKAGES=()
}

initPackagesArrays

# First try update all packages that become obsolete since this also
# means that some other packages will possibly be updated because of
# rebuilds, which may also include packages that would have been
# updated at a later stage anyways. We therefore prevent emerging the
# same package twice.
if ! $ONLY_WORLD; then
	echo "Searching for obsolete packages"
	determineObsoletePackages

	if [[ ${#UPGRADEABLE_PACKAGES[@]} -eq 0 ]] ; then
		echo "No obsolete packages found"
	elif ! ${EMERGE_ONCE}; then
		printUpgradeablePackages obsolete
		echo "${#UPGRADEABLE_PACKAGES[@]} packages that became obsolete found."
		echo "Running emerge…"
		if $PRETEND; then
			run emerge ${EMERGE_OPTS[@]} -p ${UPGRADEABLE_PACKAGES[@]}
		else
			run emerge ${EMERGE_OPTS[@]} ${EMERGE_UPDATE_OPTS[@]} ${MAYBE_EMERGE_USEPKG_OPT} ${UPGRADEABLE_PACKAGES[@]}

			if [[ ${?} -ne 0 ]]; then
				echo "Still found some more obsolete packages."
				echo "Switching to single emerge mode…"

				determineObsoletePackages
				printUpgradeablePackages obsolete

				for p in "${UPGRADEABLE_PACKAGES[@]}" ; do
					echo "Now trying to update $p"
					eix -I -e $p
					run emerge ${EMERGE_OPTS[@]} ${EMERGE_UPDATE_OPTS[@]} ${MAYBE_EMERGE_USEPKG_OPT} $p
				done
			fi
		fi

		initPackagesArrays
	fi
fi

# Then proceed with all world packages that have no fetch restrictions
# but updates
WORLD_PACKAGES=$(eix \
			   -I -u \
			   --world-file \
			   --only-names \
			   --not -\( --restrict-fetch -\) \
			   || true)

for WORLD_PACKAGE in ${WORLD_PACKAGES}; do
	# shellcheck disable=SC2091
	if $(FORMAT='{upgrade}true{else}false{}' eix --exact --pure-packages "${WORLD_PACKAGE}"); then
		# TODO: Take slots into account. If the currently
		# installed slot is upgradeable, then use this
		# slot. Otherwhise use the newest stable stlot.
		UPGRADEABLE_PACKAGES+=("${WORLD_PACKAGE}")
	else
		NON_UPGRADEABLE_PACKAGES+=("${WORLD_PACKAGE}")
	fi
done

if $EMERGE_ONCE; then
	PACKAGE_KIND="world/obsolete"
else
	PACKAGE_KIND="world"
fi

if [[ ${#UPGRADEABLE_PACKAGES[@]} -eq 0 ]] ; then
    echo "No upgradeable ${PACKAGE_KIND} packages"
else
	printUpgradeablePackages "${PACKAGE_KIND}"
    if ! $PRETEND; then
		run emerge ${EMERGE_OPTS[@]} ${EMERGE_UPDATE_OPTS[@]} ${MAYBE_EMERGE_USEPKG_OPT} ${UPGRADEABLE_PACKAGES[@]}
	fi
fi

# Reiterate over UPGRADEABLE_PACKAGES and see if they got updated. Any
# packages that did not get updates are attempted to update again
# without emerge's --update and --changed-use option.
initPackagesArrays
determineObsoletePackages
if [[ ${#UPGRADEABLE_PACKAGES[@]} -ne 0 ]] ; then
	printUpgradeablePackages "oneshot"
	if ! $PRETEND; then
		run emerge ${EMERGE_OPTS[@]} ${MAYBE_EMERGE_USEPKG_OPT} ${UPGRADEABLE_PACKAGES[@]}
	fi
fi

# Update all glsa affected packages
echo "glsa-check: Checking for packages with known vulnerabilities"
if ! run glsa-check -f affected; then
	exit "${EXIT_GLSA_FIX_FAILED}"
fi

readonly STATEDIR=/var/lib/update-system

LAST_UNATTENDED_REBOOT_REQUIRED_FILE="${STATEDIR}/last-unattended-reboot-required"

finish_update_system() {
	local exit_status
	if [[ ${#FAILED_COMMANDS[@]} -ne 0 ]]; then
		ERROR_MESSAGE_FILE=$(mktemp --tmpdir update-system-error-message.XXXXX)
		echo "ERROR: update-system on ${HOSTNAME} finished, but some commands failed:" > "${ERROR_MESSAGE_FILE}"
		printf '%s\n' "${FAILED_COMMANDS[@]}" >> "${ERROR_MESSAGE_FILE}"

		cat "${ERROR_MESSAGE_FILE}" >&2

		CREDFILE="/etc/gentools/sendxmpp.credentials"
		if command-exists sendxmpp && [[ -r "${CREDFILE}" ]]; then
			source "/etc/gentools/sendxmpp.config"

			if [[ -v RECIPIENT ]]; then
				sendxmpp send \
						 --credfile "${CREDFILE}" \
						 --recipient "${RECIPIENT}" \
						 --message - \
						 < "${ERROR_MESSAGE_FILE}"
			else
				>&2 echo "ERROR: RECIPIENT for sendxmpp not configured"
			fi
		fi

		rm "${ERROR_MESSAGE_FILE}"

		exit_status="${EXIT_FAILED_COMMANDS}"
	else
		exit_status=0
	fi

	if $REBOOT; then
		rm "${LAST_UNATTENDED_REBOOT_REQUIRED_FILE}"

		if $PRETEND; then
			echo "PRETEND: Would schedule reboot in 30 seconds"
		else
			echo "Scheduling reboot in 30 seconds"
			systemd-run --on-active=30 systemctl reboot
		fi
	fi

	exit "${exit_status}"
}

$ONLY_WORLD && finish_update_system

# Note that eix will return an non-zero exit code if no package was
# found, hence we add "|| true".
RESTRICT_FETCH_PACKAGES=$(eix -I -u --world-file --only-names --restrict-fetch || true)
if [[ -n ${RESTRICT_FETCH_PACKAGES} ]]; then
    echo "The following world packages have fetch restrictions"
    echo "Please resovle those"
    emerge -pv ${RESTRICT_FETCH_PACKAGES}
fi

if [[ ${#NON_UPGRADEABLE_PACKAGES[@]} -ne 0 ]]; then
	echo "The following packages need care (e.g. keyword adjustments)"
	for pkg in ${NON_UPGRADEABLE_PACKAGES[@]}; do
		eix $pkg
	done
fi

readonly LAST_WORLD_UPDATE_FILE="${STATEDIR}/last-world-update"

declare -ri SECONDS_PER_DAY=86400

DO_WORLD_UPDATE=false
declare -ri CURRENT_DAY_SINCE_EPOCH=$(( $(date +%s) / SECONDS_PER_DAY ))

check_last_flag_file() {
	local -r last_flag_file="${1}"
	local -ri perform_every_days="${2}"
	local -r subject="${3}"

	if [[ ! -f "${last_flag_file}" ]]; then
		echo "${last_flag_file} for ${subject} does not exist"
		return 0
	fi

	local -ri last_days=$(<"${last_flag_file}")
	local -ri last_days_ago=$(( CURRENT_DAY_SINCE_EPOCH - last_days ))

	if (( last_days_ago > perform_every_days )); then
		echo "Last ${subject} ${last_days_ago} days ago, greater than threshold of ${perform_every_days} days."
		return 0
	else
		echo "Last ${subject} ${last_days_ago} days ago, lower or equal than threshold of ${perform_every_days} days."
		return 1
	fi
}

if check_last_flag_file "${LAST_WORLD_UPDATE_FILE}" "${WORLD_UPDATE_EVERY_DAYS}" "world update"; then
   DO_WORLD_UPDATE=true
fi

if $DO_WORLD_UPDATE; then
	echo "Performing regular world update"
	run emerge ${EMERGE_OPTS[@]} ${EMERGE_UPDATE_OPTS[@]} ${MAYBE_EMERGE_USEPKG_OPT} --deep @world

	if ! $RUN_FAILED; then
		echo "${CURRENT_DAY_SINCE_EPOCH}" > "${LAST_WORLD_UPDATE_FILE}"
	fi
fi

# if command-exists perl-cleaner; then
# 	run perl-cleaner --all -- --jobs=${JOBS}
# fi

if command-exists haskell-updater; then
	run haskell-updater -- --jobs=${JOBS}
fi

if command-exists eclean-kernel && $ECLEAN_KERNEL; then
	ECLEAN_KERNEL_ARGS=(
		--num 5
	)

	if $PRETEND; then
		ECLEAN_KERNEL_ARGS+=(--pretend)
	fi

	run eclean-kernel ${ECLEAN_KERNEL_ARGS[@]}
fi

if command-exists smart-live-rebuild; then
	readonly LAST_SMART_LIVE_REBUILD_FILE="${STATEDIR}/last-smart-live-rebuild"
	if check_last_flag_file "${LAST_SMART_LIVE_REBUILD_FILE}" "${SMART_LIVE_REBUILD_EVERY_DAYS}" "smart live rebuild"; then
		SMART_LIVE_REBUILD_ARGS=(
			--jobs=${JOBS}
			--filter-packages=!app-doc/eclass-manpages
		)

		if $USEPKG; then
			SMART_LIVE_REBUILD_ARGS+=(--quickpkg)
		fi

		run smart-live-rebuild ${SMART_LIVE_REBUILD_ARGS[@]}

		if ! $RUN_FAILED; then
			echo "${CURRENT_DAY_SINCE_EPOCH}" > "${LAST_SMART_LIVE_REBUILD_FILE}"
		fi
	fi
fi

maybe_depclean() {
	if $PRETEND; then
		return 0
	fi

	local -r DEPCLEAN_INHIBITED_UNTIL_FILE=/etc/gentools/depclean-inhibited
	if [[ -f "${DEPCLEAN_INHIBITED_UNTIL_FILE}" ]]; then
		if [[ $(( $(date +"%s") - $(stat -c "%Y" "${DEPCLEAN_INHIBITED_UNTIL_FILE}") )) -gt 1814400 ]]; then
		   echo "${DEPCLEAN_INHIBITED_UNTIL_FILE} is more than 21 days old, removing"
		   rm "${DEPCLEAN_INHIBITED_UNTIL_FILE}"
		fi
		echo "${DEPCLEAN_INHIBITED_UNTIL_FILE} found, not cleaning dependencies"
		return
	fi

	if ! $DO_WORLD_UPDATE; then
		# If we did not a world update, then do not record --depclean
		# failures.
		local -x DO_NOT_RECORD_FAILURE=1
	fi

	run emerge --depclean
}

if $DEPCLEAN; then
	maybe_depclean
fi

run eclean ${ECLEAN_DISTFILES_ARGS} ${MAYBE_PRETEND} distfiles
run eclean ${MAYBE_PRETEND} packages

maybe_etckeeper_commit() {
	if ! command-exists etckeeper; then
		return
	fi
	if etckeeper unclean; then
		etckeeper commit $@
	fi
}

if command-exists portpeek; then
	maybe_etckeeper_commit "Before portpeek"
	# Portpeek would remove entries from package.env if the package is
	# not installed. However users often want to keep those
	# package.env entries, e.g., for package testing purposes.
	portpeek --no-color --keyword --mask --unmask --fix
	maybe_etckeeper_commit "After portpeek"
fi

if command-exists systemctl; then
	while read unit; do
		UNIT_NEEDS_DAEMON_RELOAD=$(systemctl show ${unit} -P NeedDaemonReload)
		if [[ "${UNIT_NEEDS_DAEMON_RELOAD}" == "yes" ]]; then
			systemctl daemon-reload
			break
		fi
	done< <(systemctl list-unit-files | awk '{print $1}' | grep -E '[^@].(service|timer)$')
fi

if "${RESTART_SERVICES}" && command-exists needrestart; then
	if $UNATTENDED_REBOOT; then
		NEEDRESTART_BATCH_FILE=$(mktemp --tmpdir update-system-needrestart-batch.XXXXX)

		echo "Invoking needrestart in batch mode to check for kernel update"
		needrestart -b > "${NEEDRESTART_BATCH_FILE}"

		if $DEBUG; then
			cat "${NEEDRESTART_BATCH_FILE}"
		fi

		NEEDRESTART_KSTA=$(sed -n 's/NEEDRESTART-KSTA: \([0-4]\)/\1/p' "${NEEDRESTART_BATCH_FILE}")

		if [[ "${NEEDRESTART_KSTA}" == 3 ]]; then
			if [[ ! -f  "${LAST_UNATTENDED_REBOOT_REQUIRED_FILE}" ]]; then
				echo "${CURRENT_DAY_SINCE_EPOCH}" > "${LAST_UNATTENDED_REBOOT_REQUIRED_FILE}"
			elif check_last_flag_file "${LAST_UNATTENDED_REBOOT_REQUIRED_FILE}" "${UNATTENDED_REBOOT_AFTER_DAYS}" "unattended reboot required"; then
				REBOOT=true
			fi
		else
			echo "Needrestart reports no kernel update pending"
		fi
	fi

	if ! $REBOOT; then
		echo "Invoking needrestart to check for services that need to be restarted"
		run needrestart -r a
	fi
fi

finish_update_system
